apiVersion: v1
kind: Template
metadata:
  name: webui_service_template
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: usquad
      name: webui
      namespace: ${NAMESPACE}
      selfLink: /api/v1/namespaces/${NAMESPACE}/services/webui
    spec:
      ports:
        - name: 80-tcp
          port: 80
          protocol: TCP
          targetPort: 80
      selector:
        deploymentconfig: webui_dc
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: usquad
      annotations:
        router.cern.ch/network-visibility: Internet
      name: webui_route
      namespace: ${NAMESPACE}
    spec:
      host: ${NAMESPACE}.web.cern.ch
      port:
        targetPort: 80-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: webui
        weight: 100
      wildcardPolicy: None
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: usquad
      name: webui_dc
      namespace: ${NAMESPACE}
      selfLink: >-
        /apis/apps.openshift.io/v1/namespaces/${NAMESPACE}/deploymentconfigs/webui
    spec:
      replicas: 3
      selector:
        app: usquad
        deploymentconfig: webui_dc
      strategy:
        
        type: Rolling
      template:
        metadata:
          labels:
            app: usquad
            deploymentconfig: webui_dc
        spec:
          containers:
            - image: >-
                gitlab-registry.cern.ch/cmcrobotics/microsquad:${IMAGE_VERSION}
              imagePullPolicy: IfNotPresent
              name: webui
              livenessProbe:
                failureThreshold: 5
                httpGet:
                  path: /
                  port: 80
                  scheme: HTTP
                initialDelaySeconds: 30
                periodSeconds: 30
                successThreshold: 1
                timeoutSeconds: 5
              readinessProbe:
                failureThreshold: 5
                httpGet:
                  path: /
                  port: 80
                  scheme: HTTP
                initialDelaySeconds: 30
                periodSeconds: 15
                successThreshold: 1
                timeoutSeconds: 15
              ports:
                - containerPort: 80
                  protocol: TCP
              resources: 
                requests:
                  cpu: 200m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: { }
          terminationGracePeriodSeconds: 30
parameters:
  - name: IMAGE_VERSION
    description: Image tag to deploy
    required: true
  - name: NAMESPACE
    description: Website namespace (hostname)
    required: true

