apiVersion: apps/v1
kind: Deployment
metadata:
  name: usquad
spec:
  selector:
    matchLabels:
      app: usquad
  replicas: 1
  template:
    metadata:
      labels:
        app: usquad
    spec:
      containers:
      - name: usquad
        image: eu.gcr.io/qualified-star-312116/web-ui
        ports:
        - containerPort: 80