apiVersion: v1
kind: Service
metadata:
  name: usquad
  labels:
    run: usquad
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: usquad
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usquad
spec:
  selector:
    matchLabels:
      run: usquad
  replicas: 1
  template:
    metadata:
      labels:
        run: usquad
    spec:
      containers:
      - name: usquad-web-ui
        image: ghcr.io/cmcrobotics/microsquad-web-ui:latest
        ports:
        - containerPort: 80