apiVersion: v1
kind: Template
metadata:
  name: web-ui-service-template
objects: 
 - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: usquad
      annotations:
        router.cern.ch/network-visibility: Internet
      name: web-ui-route
      namespace: ${NAMESPACE}
    spec:
      host: ${NAMESPACE}.web.cern.ch
      #path: ${CONTEXT_PATH}
      port:
        targetPort: 8080-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: web-ui
        weight: 100
      wildcardPolicy: None
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: usquad
      annotations:
        router.cern.ch/network-visibility: Internet
      name: mosquitto-websocket-route
      namespace: ${NAMESPACE}
    spec:
      host: ${NAMESPACE}.web.cern.ch
      path: /mqtt
      port:
        targetPort: 9001-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: mosquitto
        weight: 100
      wildcardPolicy: None

parameters:
  - name: NAMESPACE
    description: Website namespace (hostname)
    required: true
  - name: CONTEXT_PATH
    description: Web UI Context Path
    value: "/ui"
